export const dataUser = [
  {
    id: 1,
    entity: 'Juan Manuel Contreras',
    image_url: 'https://i.ibb.co/Zgq29Gy/profile.png',
    role: 'Administrador',
    mail: 'juanmanuel@example.com',
  },
  {
    id: 2,
    entity: 'Pedro Llanos',
    image_url: 'https://i.ibb.co/Zgq29Gy/profile.png',
    role: 'Inventariador',
    mail: 'pedrollanos@example.com',
  },
  {
    id: 3,
    entity: 'Ana García',
    image_url: 'https://i.ibb.co/Zgq29Gy/profile.png',
    role: 'Administrador',
    mail: 'anagarcia@example.com',
  },
  {
    id: 4,
    entity: 'María Rodríguez',
    image_url: 'https://i.ibb.co/Zgq29Gy/profile.png',
    role: 'Supervisor',
    mail: 'mariarodriguez@example.com',
  },
  {
    id: 5,
    entity: 'Luis Pérez',
    image_url: 'https://i.ibb.co/Zgq29Gy/profile.png',
    role: 'Inventariador',
    mail: 'luisperez@example.com',
  },
  {
    id: 6,
    entity: 'Laura Montes',
    image_url: 'https://i.ibb.co/Zgq29Gy/profile.png',
    role: 'Administrador',
    mail: 'lauramontes@example.com',
  },
  {
    id: 7,
    entity: 'Carlos Mendoza',
    image_url: 'https://i.ibb.co/Zgq29Gy/profile.png',
    role: 'Operador',
    mail: 'carlosmendoza@example.com',
  },
  {
    id: 8,
    entity: 'Isabel Ramos',
    image_url: 'https://i.ibb.co/Zgq29Gy/profile.png',
    role: 'Supervisor',
    mail: 'isabelramos@example.com',
  },
  {
    id: 9,
    entity: 'Jorge Herrera',
    image_url: 'https://i.ibb.co/Zgq29Gy/profile.png',
    role: 'Inventariador',
    mail: 'jorgeherrera@example.com',
  },
  {
    id: 10,
    entity: 'Carmen Morales',
    image_url: 'https://i.ibb.co/Zgq29Gy/profile.png',
    role: 'Operadora',
    mail: 'carmenmorales@example.com',
  },
  {
    id: 11,
    entity: 'Andrés Soto',
    image_url: 'https://i.ibb.co/Zgq29Gy/profile.png',
    role: 'Administrador',
    mail: 'andressoto@example.com',
  },
  {
    id: 12,
    entity: 'Natalia Silva',
    image_url: 'https://i.ibb.co/Zgq29Gy/profile.png',
    role: 'Inventariadora',
    mail: 'nataliasilva@example.com',
  },
];

