export const unitOptions = [
  { value: 'KG', description: 'Kilogramo' },
  { value: 'G', description: 'Gramo' },
  { value: 'LB', description: 'Libra' },
  { value: 'OZ', description: 'Onza' },
  { value: 'L', description: 'Litro' },
  { value: 'ML', description: 'Mililitro' },
  { value: 'GAL', description: 'Galón' },
  { value: 'M', description: 'Metro' },
  { value: 'CM', description: 'Centímetro' },
  { value: 'MM', description: 'Milímetro' },
  { value: 'PC', description: 'Pieza' },
  { value: 'DOZ', description: 'Docena' },
  { value: 'PK', description: 'Paquete' },
  { value: 'BTL', description: 'Botella' },
  { value: 'LATA', description: 'Lata' },
  { value: 'CAJA', description: 'Caja' },
  { value: 'C/U', description: 'Cada uno' },
];
