export const unitOptions = [
  { value: 'Kg', description: 'Kilogramo' },
  { value: 'g', description: 'Gramo' },
  { value: 'lb', description: 'Libra' },
  { value: 'oz', description: 'Onza' },
  { value: 'L', description: 'Litro' },
  { value: 'ml', description: 'Mililitro' },
  { value: 'gal', description: 'Galón' },
  { value: 'qt', description: 'Cuarto' },
  { value: 'pt', description: 'Pinta' },
  { value: 'fl oz', description: 'Onza fluida' },
  { value: 'm', description: 'Metro' },
  { value: 'cm', description: 'Centímetro' },
  { value: 'mm', description: 'Milímetro' },
  { value: 'in', description: 'Pulgada' },
  { value: 'ft', description: 'Pie' },
  { value: 'yd', description: 'Yarda' },
  { value: 'pc', description: 'Pieza' },
  { value: 'doz', description: 'Docena' },
  { value: 'ea', description: 'Cada uno' },
  { value: 'pk', description: 'Paquete' },
  { value: 'btl', description: 'Botella' },
  { value: 'can', description: 'Lata' },
];
