export const categoryOptions = [
  { value: '', label: 'Seleccione una categoría' },
  { value: 'limpieza', label: 'Limpieza' },
  { value: 'cuidado_personal', label: 'Cuidado Personal' },
  { value: 'bebidas', label: 'Bebidas' },
  { value: 'snacks', label: 'Snacks' },
  { value: 'frutas_verduras', label: 'Frutas y Verduras' },
  { value: 'carnes', label: 'Carnes y Pescados' },
  { value: 'panaderia', label: 'Panadería' },
  { value: 'productos_limpieza', label: 'Productos de Limpieza' },
  { value: 'maquillaje', label: 'Maquillaje' },
  { value: 'perfumes', label: 'Perfumes' },
  { value: 'shampoo_acondicionador', label: 'Shampoo y Acondicionador' },
  { value: 'jabones', label: 'Jabones' },
  { value: 'detergentes', label: 'Detergentes' },
  { value: 'cepillos_peines', label: 'Cepillos y Peines' },
  { value: 'cuidado_piel', label: 'Cuidado de la Piel' },
  { value: 'cuidado_cabello', label: 'Cuidado del Cabello' },
  { value: 'cuidado_bucal', label: 'Cuidado Bucal' },
  // Agrega más opciones según tus necesidades
];
